### PR TITLE
Shiva.jena _feature-changes-to-written docs

### PR DESCRIPTION
**Pull request by shivajena**

### CODE REVIEW

**Review by imtvwy — APPROVED** [review]
Please add the link to the EDA literal document in the EDA section.  The link should point to "https://github.com/UBC-MDS/Giant_Pumpkins_Weight_Prediction/tree/main/src/eda//pumpkin_eda.pdf"

Can use this link "https://github.com/UBC-MDS/Giant_Pumpkins_Weight_Prediction/tree/main/doc" for the analysis report

**Review by Rowansiv — COMMENTED** [review]
The project proposal reads well.
Few minor changes to punctuation if possible but not necessary.

**Comment by shivajena** [comment]
> Please add the link to the EDA literal document in the EDA section. The link should point to "https://github.com/UBC-MDS/Giant_Pumpkins_Weight_Prediction/tree/main/src/eda//pumpkin_eda.pdf"
> 
> Can use this link "https://github.com/UBC-MDS/Giant_Pumpkins_Weight_Prediction/tree/main/doc" for the analysis report

For EDA, I have added links to src folder ipynb file for now since pdf isnt there yet. We can always edit the links it is not a big deal.
For analysis report also, added the link.

**Comment by shivajena** [comment]
> 

Thank you! We can discuss the punctuation or any other issues as we make changes going forward.  For now, made very minimal minor changes as I wasnt able to clearly spot them.

**Pull request merged**
